import { AchievementCardElement } from "../types/_types";

export const achievements: AchievementCardElement[] = [
  {
    achievementId: "1",
    achievementName: 'Gikk mer enn 3 km',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 2 - Trygge Soner',
    Date: new Date('August 18, 2020 20:10:30'),
  },
  {
    achievementId: "2",
    achievementName: 'Startet tracking første gang',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 19, 2020 23:15:30'),
  },
  {
    achievementId: "3",
    achievementName: 'Tracket 5 dager på rad',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 3 - Varig Insats',
    Date: new Date('August 18, 2020 23:17:30'),
  },
  {
    achievementId: "4",
    achievementName: 'Gikk til jobb dag 2',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 18, 2020 21:32:30'),
  },
  {
    achievementId: "5",
    achievementName: 'Syklet i grønn sone',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 2 - Trygge Soner',
    Date: new Date('August 19, 2020 20:19:30'),
  },
  {
    achievementId: "6",
    achievementName: 'Satte igjen bilen hjemme',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 18, 2020 21:18:30'),
  },
  {
    achievementId: "7",
    achievementName: 'Gikk til jobb 1 dag',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 20, 2020 19:35:30'),
  },
  {
    achievementId: "8",
    achievementName: 'Varig insats',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 2 - Trygge Soner',
    Date: new Date('August 19, 2020 21:56:30'),
  },
  {
    achievementId: "9",
    achievementName: 'Gikk tur i grønn sone',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 2 - Trygge Soner',
    Date: new Date('August 20, 2020 22:56:30'),
  },
  {
    achievementId: "10",
    achievementName: 'Gikk til jobb 2 dager',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 20, 2020 12:25:30'),
  },
  {
    achievementId: "11",
    achievementName: 'Tur 3 dager på rad',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 3 - Varig Insats',
    Date: new Date('August 19, 2020 21:12:30'),
  },
];
