export const achievements = [
  {
    achievementSymbol: 0x1f648,
    achievementName: 'Gikk mer enn 3 km',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 2 - Trygge Soner',
    Date: new Date('August 18, 2020 20:10:30'),
  },
  {
    achievementSymbol: 0x1f649,
    achievementName: 'Startet tracking første gang',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 19, 2020 23:15:30'),
  },
  {
    achievementSymbol: 0x1f64a,
    achievementName: 'Tracket 5 dager på rad',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 3 - Varig Insats',
    Date: new Date('August 18, 2020 23:17:30'),
  },
  {
    achievementSymbol: 0x1f921,
    achievementName: 'Gikk til jobb dag 2',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 18, 2020 21:32:30'),
  },
  {
    achievementSymbol: 0x1f479,
    achievementName: 'Syklet i grønn sone',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 2 - Trygge Soner',
    Date: new Date('August 19, 2020 20:19:30'),
  },
  {
    achievementSymbol: 0x1f47a,
    achievementName: 'Satte igjen bilen hjemme',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 18, 2020 21:18:30'),
  },
  {
    achievementSymbol: 0x1f47b,
    achievementName: 'Gikk til jobb 1 dag',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 20, 2020 19:35:30'),
  },
  {
    achievementSymbol: 0x1f47c,
    achievementName: 'Varig insats',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 2 - Trygge Soner',
    Date: new Date('August 19, 2020 21:56:30'),
  },
  {
    achievementSymbol: 0x1f47d,
    achievementName: 'Gikk tur i grønn sone',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 2 - Trygge Soner',
    Date: new Date('August 20, 2020 22:56:30'),
  },
  {
    achievementSymbol: 0x1f47e,
    achievementName: 'Gikk til jobb 2 dager',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 1 - Gå til Jobb',
    Date: new Date('August 20, 2020 12:25:30'),
  },
  {
    achievementSymbol: 0x1f480,
    achievementName: 'Tur 3 dager på rad',
    achievementDescription: 'Du er flink!',
    achievementGroup: 'Gruppe 3 - Varig Insats',
    Date: new Date('August 19, 2020 21:12:30'),
  },
];
