/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id:
    'eu-central-1:dd678550-a489-45f7-ac98-30536b49551c',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_Qt8vhCEWi',
  aws_user_pools_web_client_id: '6ab2cb0f4t41oatug62kaqs84f',
  oauth: {},
};

export default awsmobile;
